package cn.nongdewang;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class AutoGeneratedMybatisMysqlApplication {

	public static void main(String[] args) {
		SpringApplication.run(AutoGeneratedMybatisMysqlApplication.class, args);
	}
}
